---
- name: Cluster prerequisite
  hosts: k3s_cluster
  tags: [cluster-prep]
  gather_facts: true
  become: true
  roles:
    - role: prereq

- name: Airgap configuration
  hosts: k3s_cluster
  tags: [cluster-airgap]
  gather_facts: true
  become: true
  roles:
    - role: airgap

- name: Raspberrypi configuration
  hosts: k3s_cluster
  tags: [cluster-rasberry]
  gather_facts: true
  become: true
  roles:
    - role: raspberrypi

- name: Ansible role pip configuration
  hosts: k3s_cluster
  tags: [cluster-pip]
  gather_facts: true
  become: true
  roles:
    - role: ansible-role-pip

- name: Ansible role PyratLabs configuration
  hosts: k3s_cluster
  tags: [cluster-pyratlab]
  gather_facts: true
  become: true
  roles:
    - role: ansible-role-k3s

- name: Setup K3S server
  hosts: server
  tags: [k3s-server-setup]
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  tags: [k3s-agent-setup]
  become: true
  roles:
    - role: k3s_agent
