---
# Prometheus only need to be installed on one of the node and it will find rest of the nodes

- name: Install prometheus on master
  hosts: server
  become: true
  gather_facts: true
  tasks:
    - name: Install prometheus
      kubernetes.core.helm:
        name: prometheus
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        chart_ref: kube-prometheus-stack
        chart_version: "55.5.0"
        release_namespace: monitoring
        create_namespace: true
        release_name: prometheus
        values:
          nameOverride: "prometheus"
          fullnameOverrride: "prometheus"
          coreDns:
            enabled: false
          kubeDns:
            enabled: true
          alertmanager:
            alertmanagerSpec:
              nodeSelector:
                kubernetes.io/hostname: london-2
          grafana:
            imageRenderer:
              nodeSelector:
                kubernetes.io/hostname: london-2
            nodeSelector:
              kubernetes.io/hostname: london-2
          kube-state-metrics:
            nodeSelector:
              kubernetes.io/hostname: london-2
          prometheus:
            prometheusSpec:
              nodeSelector:
                kubernetes.io/hostname: london-2
          prometheus-node-exporter:
            nodeSelector:
              kubernetes.io/hostname: london-2
          prometheusOperator:
            admissionWebhooks:
              deployment:
                nodeSelector:
                  kubernetes.io/hostname: london-2
              patch:
                nodeSelector:
                  kubernetes.io/hostname: london-2
            nodeSelector:
              kubernetes.io/hostname: london-2
          thanosRuler:
            thanosRulerSpec:
              nodeSelector:
                kubernetes.io/hostname: london-2
        state: present
