---
# Prometheus only need to be installed on one of the node and it will find rest of the nodes

- name: Install prometheus on master
  hosts: server
  become: true
  gather_facts: true
  tasks:
    - name: Install prometheus
      kubernetes.core.helm:
        name: prometheus
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        chart_ref: kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        release_name: prometheus
        values:
          alertmanager:
            alertmanagerSpec:
              nodeSelector:
                kubernetes.io/hostname: london
          grafana:
            imageRenderer:
              nodeSelector:
                kubernetes.io/hostname: london
          grafana:
            nodeSelector:
              kubernetes.io/hostname: london
          kube-state-metrics:
            nodeSelector:
              kubernetes.io/hostname: london
          prometheus:
            prometheusSpec:
              nodeSelector:
                kubernetes.io/hostname: london
          prometheus-node-exporter:
            nodeSelector:
              kubernetes.io/hostname: london
          prometheusOperator:
            admissionWebhooks:
              deployment:
                nodeSelector:
                  kubernetes.io/hostname: london
              patch:
                nodeSelector:
                  kubernetes.io/hostname: london
            nodeSelector:
              kubernetes.io/hostname: london
          thanosRuler:
            thanosRulerSpec:
              nodeSelector:
                kubernetes.io/hostname: london
        state: present
