---
# Prometheus only need to be installed on one of the node and it will find rest of the nodes

- name: Install prometheus on master
  hosts: server
  become: true
  gather_facts: true
  tasks:
    - name: Install prometheus
      kubernetes.core.helm:
        name: prometheus
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        chart_ref: kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        release_name: prometheus

        state: present
