---
- name: Uninstall prometheus on master
  hosts: server
  become: true
  gather_facts: true

  tasks:
    - name: Uninstall prometheus
      kubernetes.core.helm:
        purge: yes
        release_name: prometheus
        chart_ref: kube-prometheus-stack
        release_namespace: monitoring
        state: absent
