---
### Cert manager

- name: Install cert manager on master
  hosts: server
  become: true
  gather_facts: true
  tasks:
    - name: Install cert manager
      kubernetes.core.helm:
        name: cert-manager
        chart_repo_url: https://charts.jetstack.io
        chart_ref: cert-manager
        release_namespace: cert-manager
        create_namespace: true
        release_name: cert-manager
        values:
          installCRDs: true
        state: present

    - name: Configure Cluster Issuer
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer # I'm using ClusterIssuer here
          metadata:
            name: letsencrypt-prod
          spec:
            acme:
              server: https://acme-v02.api.letsencrypt.org/directory
              email: "{{ email }}"
              privateKeySecretRef:
                name: letsencrypt-prod
              solvers:
                - http01:
                    ingress:
                      class: traefik
