--- 

- name: Create directory /nvim
  ansible.builtin.file:
    path: /nvim
    state: directory
    mode: 0755

- name: Download NeoVim AppImage
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /nvim
    mode: "u+x"

- name: Create directory /opt/nvim
  file:
    path: /opt/nvim
    state: directory
    mode: "644"

    # FIXME: this didn't happen maybe because the file was already there?
- name: Move nvim.appimage to /opt/nvim/nvim
  ansible.builtin.copy: 
      src: /nvim/nvim.appimage 
      dest: /opt/nvim
      remote_src: true
      mode: "preserve"
   

- name: Add export PATH to ~/.bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH="$PATH:/opt/nvim/"'
    create: true

- name: Extract NeoVim AppImage
  ansible.builtin.shell: ./nvim.appimage --appimage-extract
  args:
    chdir: /opt/nvim

- name: Remove /usr/bin/nvim if it exists
  ansible.builtin.file:
    path: /usr/bin/nvim
    state: absent

- name: Expose NeoVim globally
  ansible.builtin.file:
    src: /opt/nvim/squashfs-root/AppRun 
    dest: /usr/bin/nvim
    state: link

- name: Check if nvim config exists
  ansible.builtin.stat:
    path: ~/.config/nvim
  register: nvim_config

- name: Do a backup on the current nvim config
  ansible.builtin.copy:
    src: ~/.config/nvim 
    dest: ~/.config/nvim.bak
    remote_src: true
  when: nvim_config.stat.exists

- name: Clone a nvim config repo 
  git: 
    repo: https://github.com/kerwanp/nvim.git
    dest: ~/.config/nvim
    clone: true
    update: true
