--- 

- name: Create directory /nvim
  ansible.builtin.file:
    path: /nvim
    state: directory
    mode: 0755

- name: Download NeoVim AppImage
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /nvim
    mode: "u+x"

- name: Create directory /opt/nvim
  file:
    path: /opt/nvim
    state: directory
    mode: "0755"

    # FIXME: this didn't happen maybe because the file was already there?
- name: Move nvim.appimage to /opt/nvim/nvim
  ansible.builtin.copy: 
      remote_src: /nvim/nvim.appimage 
      dest: /opt/nvim
      args:
        creates: /opt/nvim/nvim
        register: move_result

- name: Display move command result
  ansible.builtin.debug:
    msg: "{{ move_result.stdout_lines }}"

- name: Add export PATH to ~/.bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH="$PATH:/opt/nvim/"'
    create: yes

- name: Extract NeoVim AppImage
  ansible.builtin.shell: | 
      /opt/nvim/nvim.appimage --appimage-extract

- name: Expose NeoVim globally
  ansible.builtin.file:
    src: /opt/nvim/squashfs-root/AppRun 
    dest: /usr/bin/nvim
    state: link
    args:
      creates: /usr/bin/nvim
      become: yes

- name: Do a backup on the current nvim config
  ansible.builtin.copy:
    remote_src: ~/.config/nvim 
    dest: ~/.config/nvim.bak
    args:
      creates: ~/.config/nvim.bak

- name: Clone a nvim config repo 
  git: 
    repo: https://github.com/kerwanp/nvim.git
    dest: ~/.config/nvim
    clone: yes
    update: yes
