---
- name: Preparation for Kubernetes
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Set unattended-upgrades configuration
      debconf:
        name: unattended-upgrades
        question: "unattended-upgrades/enable_auto_updates"
        value: "true"
        vtype: boolean
      register: result
      ignore_errors: yes

    - name: Check if debconf value was set
      debug:
        msg: "unattended-upgrades configuration set successfully"
      when: result.changed

    - name: Install required packages including git
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - wget
        - sudo

    - name: Update package lists
      apt: update_cache=yes

    - name: Ensure time synced with NTP
      apt: name=ntp state=present

    - name: Start NTP service
      service: name=ntpd state=started enabled=yes

    - name: Check if nvim app image exists
      stat:
        path: /opt/nvim/nvim.appimage
      register: nvim_app

    - name: Import nvim task if nvim.appimage does not exists
      import_tasks: nvim.yml
      when: not nvim_app.stat.exists
