---
# Remove EXTERNALLY-MANAGED file if we're on Debian12
# Related issue: https://github.com/geerlingguy/ansible-role-pip/issues/57
- name: Get python3 version installed
  ansible.builtin.command: python3 --version
  register: py3ver
  changed_when: false

- name: Remove EXTERNALLY-MANAGED
  ansible.builtin.file:
    path: /usr/lib/python3.11/EXTERNALLY-MANAGED
    state: absent
  when: py3ver is defined and py3ver.stdout.find("3.11") != -1
